### ISSUE TITLE
Can't able to sign-up

### ISSUE THREAD

**Issue by RajsundarCogent** [theviralboy/instagram-firebase#2]
When i tried to create a signup in Register page with firebase - "Register.jsx:74 Uncaught (in promise) FirebaseError: Missing or insufficient permissions."

**Comment by sahilverma-dev** [comment]
> When i tried to create a signup in Register page with firebase - "Register.jsx:74 Uncaught (in promise) FirebaseError: Missing or insufficient permissions."

It is fixed now. Thanks for telling me.

**Comment by Ashu1864** [comment]
How to fix this issue I am also facing this issue in my PWA app. Please help me
![Screenshot from 2023-01-24 14-48-22](https://user-images.githubusercontent.com/89795159/214253878-5eba2878-e847-48a8-922a-84b7f2b36d37.png)
